---
- name: Deploy landing page
  hosts: webserver
  become: true

  tasks:
    - name: Pull landing page image from Docker Hub
      docker_image:
        name: ikanpaus/landingpage:v4
        state: present

    - name: Run landing page container
      docker_container:
        name: landingpage
        image: ikanpaus/landingpage:v4
        state: started
        ports:
          - "80:80"
