---

    - name: Install package 
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl 
          - gnupg 
        state: latest
        # OTOMATIS DOWNLOAD KE VERSI TERTINGGI

    - name: add apt key 
      apt_key:
      # DOWNLOAD KEY BUAT APT
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository:
      # UNTUK NAMBAH REPOSITORY KE APT
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    
    - name: install docker 
      apt:
        pkg: 
          - docker-ce
          - docker-ce-cli
          - containerd.io 
          - docker-buildx-plugin 
          - docker-compose-plugin
        state: latest
        
    - name: apt install pip
      apt:
        name: python3-pip

    - name: pip install docker
      pip:
        name: docker
      notify:
        - start docker

    - name: Pull landing page image from Docker Hub
      docker_image:
        name: ikanpaus/landingpage:v4
        state: present

    - name: Run landing page container
      docker_container:
        name: landingpage
        image: ikanpaus/landingpage:v4
        state: started
        ports:
          - "80:80"

    - name: Create web directory
      file: path=test/ mode=775 state=directory

    - name: Copy file 
      template: src=test.txt dest=test/test.txt